CREATE TABLE beat
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    genre VARCHAR(255),
    image VARCHAR(255),
    price DECIMAL,
    CONSTRAINT pk_beat PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

CREATE TABLE audio
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wav       VARCHAR(255),
    mp3       VARCHAR(255),
    track_out VARCHAR(255),
    CONSTRAINT pk_audio PRIMARY KEY (id)
);

ALTER TABLE "beat"
    ADD COLUMN load_date date,
    ADD COLUMN audio_id BIGINT,
    ADD CONSTRAINT FK_BEAT_ON_AUDIO FOREIGN KEY (audio_id) REFERENCES audio (id);

ALTER TABLE "user"
    ADD COLUMN password VARCHAR(255) NOT NULL default 'defaultValue';

CREATE TABLE "order"
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    status  INTEGER,
    payment INTEGER,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE TABLE purchase
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT                                  NOT NULL,
    beat_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_purchase PRIMARY KEY (id)
);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_BEAT FOREIGN KEY (beat_id) REFERENCES beat (id);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE "beat"
    ADD COLUMN bpm INTEGER,
    ADD COLUMN key VARCHAR(255),
    ALTER COLUMN audio_id SET NOT NULL;
